#= 
    This code was generated by test version
    
=#

function Platform()

### create default constants
mm_constants_ = NamedTuple{(
  :Vmax,:Km,
)}(Float64[
  0.1,2.5,
])

### create default output
mm_output_ = Symbol[
  :S,:P,
]

### initialization of ODE variables and Records
function mm_start_(cons)
    #(Vmax,Km,) = cons

    # Heta initialize
    t = 0.0 # initial time
    P = 0.0
    S = 10.0
    default_comp = 1.0
    r1 = cons[1] * S / (cons[2] + S) * default_comp
    
    # save results

    return (
        Float64[
            S * default_comp,
            P * default_comp,
        ],
        Float64[
            default_comp,
        ]
    )
end

### calculate RHS of ODE
function mm_ode_(du, u, p, t)
    cons = p.constants
    (default_comp,) = p.static
    (S_,P_,) = u 

    # Heta rules
    P = P_ / default_comp
    S = S_ / default_comp
    r1 = cons[1] * S / (cons[2] + S) * default_comp
    
    #p.static .= [default_comp,]
    du .= [
      -r1,  # dS_/dt
      r1,  # dP_/dt
    ]
end

### output function
function mm_make_saving_(outputIds::Vector{Symbol})
    function saving_(u, t, integrator)
        cons = integrator.p.constants
        (default_comp,) = integrator.p.static
        (S_,P_,) = u

        # Heta rules
        P = P_ / default_comp
        S = S_ / default_comp
        r1 = cons[1] * S / (cons[2] + S) * default_comp
        
        # force amount

        d = Base.@locals
        return [d[id] for id in outputIds]
    end
end

### time events

### discrete events

### continous events

### event assignments


### model

mm_model_ = Model(
  mm_start_,
  mm_ode_,
  [
  ],
  mm_make_saving_,
  mm_constants_,
  mm_output_;
  title = "mm",
  free_constants = NamedTuple{(
  )}([
  ])
)

### OUTPUT

models = (
    mm = mm_model_,
)
tasks = ()

return (models, tasks,)

end
