name: Documentation

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm

      - name: Create files
        run: |
          npm ci
          npm run jsdoc
          npm run jsdoc:sitemap
          cp -f src/builder/declaration-schema.json docs
          touch docs/.nojekyll

      - name: Deploy to gh-pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
          clean: true
