# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Autotests

on:
  push:
    branches: [ master, '*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pull-requests: read

jobs:
  multios:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Autotest
      run: npm test
      env:
        CI: true
  standalone:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm ci
    - name: Build and check package
      run: |
        npm run pkg
        dist/heta-compiler-linux --version
