name: On release

on: 
    release:
        types: [created]

jobs:
    upload-release-asset:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 16.x
        - run: npm ci
        - name: Build standalone apps
          run: npm run pkg

        - name: Upload Release Asset Win
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }} # This is part of the GitHub Actions context
            asset_path: dist/heta-compiler-win.exe
            asset_name: heta-compiler-win.exe
            asset_content_type: application/octet-stream

        - name: Upload Release Asset Linux
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }} # This is part of the GitHub Actions context
            asset_path: dist/heta-compiler-linux
            asset_name: heta-compiler-linux
            asset_content_type: application/octet-stream

        - name: Upload Release Asset Macos
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }} # This is part of the GitHub Actions context
            asset_path: dist/heta-compiler-macos
            asset_name: heta-compiler-macos
            asset_content_type: application/octet-stream